### ISSUE TITLE
Rails 4.0 Upgrade Problems

### ISSUE THREAD

**Issue by nonfungibletunji** [spree-contrib/spree_product_groups#25]
gemfile below:
# gem 'spree', github: 'spree/spree'

gem 'spree', github: 'spree/spree', branch: '2-1-stable'
# gem 'spree_auth_devise', github: 'spree/spree_auth_devise'

gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '2-1-stable'

gem 'spree_multi_slideshow', '~> 1.3.0'
# gem 'spree_product_groups', github: 'spree/spree_product_groups', branch: '2-1-stable'
# gem 'spree_bootstrap', :git => 'git://github.com/stunjiturner/spree_bootstrap.git'

gem 'spree_bootstrap', github: 'jdutil/spree_bootstrap'

error below:

/Users/sturner/.rvm/gems/ruby-1.9.3-p125/gems/activemodel-4.0.0/lib/active_model/deprecated_mass_assignment_security.rb:17:in `attr_accessible':`attr_accessible`is extracted out of Rails into a gem. Please use new recommended protection model for params(strong_parameters) or add`protected_attributes`to your Gemfile to use old one. (RuntimeError)
    from /Users/sturner/.rvm/gems/ruby-1.9.3-p125/bundler/gems/spree_product_groups-5757a07b06c4/app/models/spree/product_group.rb:45:in`class:ProductGroup'

I added the gem 'protected_attributes' to my main spree app, but it caused my controllers to fail? any suggestions?

**Comment by jumph4x** [comment]
Did you mean Rails 4.0? Ruby is only up to 2.X or so :+1: 

Editing title.

**Comment by nonfungibletunji** [comment]
yes

**Comment by nonfungibletunji** [comment]
i mean rails 4 and ruby 2

**Comment by radar** [comment]
This should now be fixed. Please try again.

**Comment by nonfungibletunji** [comment]
good now
